### PR TITLE
doc: autoprogram & configuration

### PR DESCRIPTION
**Pull request by Exirel**
I stole the work from #1274 by @nfearnley to addapt it to the latest changes in the codebase (rework of Sopel's cli in particular).

I had almost nothing to do: check things here and there, and here we go.

Quick notes:

* I had to trick the autoprogram directive to prevent the `legacy` sub-command to appear
* `:maxdepth: 1` shows only the fisrt-level of the command, ie. none of its sub-commands
* public sub-commands are listed manually, but they still use autoprogram at its best

Again, thank you @nfearnley for your work, I make sure to co-author everything. I didn't know about `sphinxcontrib-autoprogram`, and it's a great addition to my toolkit—and to the Sopel project!

----

Remaining tasks:

  - [x] Restructure the documentation to prevent duplication in man page 1 and 3
  - [x] Do something about the old Willie man page
  - [x] Finalize page names (e.g. @dgw already started on documenting some of the CLI stuff, but called the file `cli.rst` instead of `cmd.rst`)
  - [x] Update documentation of logging after #1512 is merged
  - [x] Update documentation of auth after #1513 is merged
  - [x] Update documentation of flood burst after #1518 is merged
  - [x] Update documentation of logging *again* since #1547 has been merged

Other PRs being newer than this one, they will have to adapt after this is merged.

### CODE REVIEW

**Comment by nfearnley** [comment]
Thanks for taking a look at this. I don't think I would have had the time
to make any more progress on it, and I'm glad the work is going to good
use.

**Comment by dgw** [comment]
@nfearnley Thank you for giving us a starting point! We'll put it to good use.

@Exirel I'll make a bit of a to-do list here based on what was desired in the previous PR, and comments I have for this one. Don't be surprised if I edit your top comment to add a task list. :)

**Comment by Exirel** [comment]
Here is a preview of the last commit "doc: split cli&config doc from package doc":

Capture d’écran - 2019-04-24 à 09 06 10

Pretty neat, I think. This helps to generate 3 man page: section 1, 3, and 5, respectively command line calls, library calls, and configuration file format.

**Comment by Exirel** [comment]
@dgw no more willie.man. I tried to reuse as many ideas as possible. I'm sure it's possible to do even better (but it's getting late), so feedback's welcome!

I'm not sure what you mean about the last checkbox though: I reorganize few files but kept them in the same directory. It's possible to move them around if needed, but that's not mandatory to express a different hierarchy of content.

And I renamed the `cmd.rst` file into `cli.rst` because it's much better.

**Comment by Exirel** [comment]
The last commit ("doc: split [core] documentation and CoreSection") is an attempt to rework the documentation of Sopel's configuration. I'd like to keep everything related to `sopel.config` into the `config.rst` file, while having a user-friendly documentation in `configure.rst`.

As we have seen in the past on IRC, some users are confused by the documentation of the `CoreSection` object: the link between `CoreSection.some_attr` and `config.core.some_attr` is not trivial for non-developers (it's not that obvious for python developers either).

I think this is an opportunity to describe how to configure Sopel's feature with user in mind, by grouping related options together.

**Comment by Exirel** [comment]
Waiting on #1512, #1513, and #1518 to be merged.

**Comment by dgw** [comment]
@Exirel I chose #1512 for merging today, so you could check off one of those tasks.

Or you can wait until all three are merged. 😁

**Comment by Exirel** [comment]
Oh yeah!

**Comment by Exirel** [comment]
Logging documentation: done!

**Comment by dgw** [comment]
🎉 @Exirel! I just merged #1513, so you can finish this off for real at your leisure.

Note that in c067e4a7 (NEWS file update for that PR on my long-running changelog branch for 7.0) I linked to a section titled "Authentication". Instead of leaving a line note, I'll just ask here that you change the section title when you do the rewrite. 😸

**Comment by Exirel** [comment]
@dgw I'm done with this part. I think it's a good step toward a better documentation.

In the last few weeks, I've seen multiple questions on how to configure the bot (authentications, loggings, etc.), and I noticed a pattern: the current documentation for the configuration is not user-friendly enough.

What I suggest in this PR is a more feature-oriented approach to document our configuration. There is certainly room for improvement, which can be done in future PRs. For example, I didn't document the database configuration, or even the basic server connection.

So, have fun reading all of that. I know you are the king of editing, and I'm ready to take your 30-40 comments that will inevitably comes to chase all the mistake I make because of a very poor English grammar. At this point, you know me and my nemesis enough, right? :grin:

**Comment by Exirel** [comment]
I did the last bit in #1646 - and even more!

**Pull request closed without merging**
