### PR TITLE
core: properly truncate long messages with 2-byte characters

### LINKED ISSUE #467: [core]: Unicode issue in long messages
There is a bug concerning unicode characters when a message is long enough.

Here, where the message is short, everything works correctly:

<pre>
Erethon: !in 10s τεστ
BuildTest: Erethon: Okay, will remind in 10 secs
BuildTest: Erethon: τεστ
</pre>

But, when the message is long enough:

<pre>
Erethon: !in 10s 
αααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααα
BuildTest: Erethon: Okay, will remind in 10 secs
BuildTest: Erethon: 
Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î
</pre>

This is marked as [core] because it happens in more than one module, I've confirmed it in ".py" too.
I'm using python 2.7.3 and latest Willie version from master branch and I've installed Willie by running 'python setup.py install'.

### PR DESCRIPTION
**Pull request by Exirel**
When a module wants to send a multi-line message, the `Bot.say` method can be used with a `max_messages` parameter to do so. The low-level `write` method on the other hand, will truncate and discard the excess no matter what.

In both case, we must not truncate unicode character composed of 2 bytes in half: we must remove the whole unicode character, then check the size again, until the encoded message's length is lower or equal to the maximum length.

It won't solve the case where the bot can send a valid message, but the server won't be able to propagate it properly to other clients because it has to add extra information (such as the bot's hostmask and all) and such a way that it generates a message too long.

But it's a good start to fix #467

### CODE REVIEW

**Comment by Exirel** [comment]
The checkstyle script didn't like my usage of `unicode`... in the name of a test function!

So I changed it from `test_something_something_unicode()` to something else. It's fine.

**Comment by Exirel** [comment]
And now it pass. 👍

**Comment by kwaaak** [comment]
Linking issues https://github.com/sopel-irc/sopel/issues/1328 and https://github.com/sopel-irc/sopel/issues/1322 for completeness

**Comment by dgw** [comment]
> The checkstyle script didn't like my usage of `unicode`... in the name of a test function!

I was curious enough to dig out the previous build log…

````
./test/test_tools.py
ERROR: Above files use unicode() but do not make it safe for Python 3.
````

That's actually kind of hilarious, I have to say, and probably bad enough to be considered a bug in `checkstyle.sh` if you feel like fixing that in a separate PR:

https://github.com/sopel-irc/sopel/blob/cf4bccf4b98d429e9ef9b531e996be2ec92ba82b/checkstyle.sh#L46-L59

That "(heuristically)" is the problem. :laughing:

**Comment by Exirel** [comment]
Ok, I found several issues here and there. The hostmask could be a good start, but there are way more things to consider.

For example, most module just use "say" without allowing for multi-line response. Which is bad because there is not much we can do here.

And, of course, there is this whole "hostmask" situation that is a total mess and oh my I don't know where to start...

... so this will wait a bit, the time for me to figure out better overall solution.

**Comment by Exirel** [comment]
> For example, most module just use "say" without allowing for multi-line response. Which is bad because there is not much we can do here.

I was thinking about it. I think it's safe to merge this PR as-is. After all, we make sure here to never send a message that is longer than what the IRC protocol say to.

Because of the hostmask, after this PR, the problem will be only when the IRC server broadcast the bot's message to its clients. So that can be for later!

**Pull request merged**
