### PR TITLE
Replace deprecated gist API in help

### LINKED ISSUE #1254: Anonymous gists are going away. Help module will break.
GitHub [announced](https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/) last month that anonymous gist creation will be disabled on March 19, 2018 (UTC).

The `help` module was modified in fa89eb7 to essentially paste its output to a gist and simply return the link, and this functionality will break (as of writing) tomorrow. `.help` (or `.commands`) will return an error until (and unless) the module is updated to paste its contents elsewhere and/or create a static HTML file instead as I originally proposed in #1080.

(As an aside, I've been meaning to implement that HTML mode for ages. Maybe this is the kick I needed to finally get off my arse and write it. We'll see.)

### PR DESCRIPTION
**Pull request by hekel**
Resolves #1254

### CODE REVIEW

**Comment by dgw** [comment]
Just as a general comment, replacing gists with another service that supports HTTPS would be ideal. Something like https://ptpb.pw/ perhaps?

**Comment by kwaaak** [comment]
I like Hastebin (https://hastebin.com/about.md), a service with some ephemerality would be a good choice. Expiration in well under 24 hours should be more than enough.

**Comment by dgw** [comment]
@anarcat See #1080 for one reason why Sopel no longer simply dumps the command list _en masse_. That said, changing from Gist to another pastebin provider (ix.io is not final) is merely one part of the solution. Eventually the plan is to have a local HTML/text option that can be hosted from the server Sopel runs on, and perhaps also have an option to turn the "deluge of PMs" method back on if it's really wanted.

**Comment by anarcat** [comment]
hmm... yeah okay, that makes sense - thanks!

**Comment by dgw** [comment]
@anarcat, want to take a second look before I merge this?

**Comment by anarcat** [comment]
LGTM.

**Pull request merged**
