### PR TITLE
isort: add isort to the QA tools

### PR DESCRIPTION
**Pull request by Exirel**
This is a "DO ALL THE THING" kind of PR.

I know I used a very opinionated config for isort, but I stand by it. After a while, you just stop caring about your imports: isort does it for you.

In our case:

1. add some imports
2. run `make isort`
3. run `make quality`

And voilà. Your imports will be sorted and checked for quality with isort and flake8.

Note: I'm fully prepared to rebase and fix every merge conflict that will eventually happen next.
I'm ready.

:fr: :rage1:

### CODE REVIEW

**Comment by dgw** [comment]
We talked already on IRC about why I want to push this back, but I forgot to actually _do_ it. :joy_cat:

**Comment by dgw** [comment]
Starting to look ahead at what needs doing for 7.1, and it would be good to get this and/or my own `flake8-import-order` [branch](https://github.com/dgw/sopel/tree/flake8-import-order) squared away early before any other major PRs get going.

@Exirel, I have a couple questions about this:

1. Did you choose `isort` purely because it can use the same config for both checking and auto-sorting? I'm mostly curious what (if any) advantages there are to using `isort` over a flake8 plugin besides the obvious utility of having a `make isort` action available, since all of our other checks run through flake8.
2. Assuming we go forward with `isort`, can we make it not split _all_ our required `__future__` imports onto 6 lines? That's pretty unsightly; just alphabetizing them is enough.

**Comment by Exirel** [comment]
1. because `isort` can fix the import order or check if the import order is respected or both
2. I don't know yet, but considering that `__future__` will get thrown out of the way with Py3... 😄  I'll have a look.

**Comment by dgw** [comment]
Quickly dropping by here with the work-in-progress `isort` config I've been playing with, on top of #1864. It's mostly a superset of the one in this PR; the one difference is `line_length` (but that only needs to be `85` to keep our future imports on one line).

```ini
[isort]
default_section = THIRDPARTY
force_sort_within_sections = True
include_trailing_comma = True
known_first_party = sopel
line_length = 120
lines_after_imports = 2
lines_between_types = 1
multi_line_output = 3
use_parentheses = True
```

**Comment by half-duplex** [comment]
Mine+dgw's, this gets closer to matching the current style:
```ini
[isort]
atomic = true
default_section = THIRDPARTY
force_sort_within_sections = true
include_trailing_comma = true
known_first_party = sopel
line_length = 99
lines_after_imports = 2
multi_line_output = 3
not_skip = __init__.py
reverse_relative = true
no_lines_before = LOCALFOLDER
```

Some remaining conflicts:
case_sensitive defaults to false and only seems to change module name sorting
```diff
-from sopel.tools import deprecated, Identifier
+from sopel.tools import Identifier, deprecated
```
I don't even know what this is trying to do
```diff
@@ -11,7 +11,6 @@
 
 import collections
 from datetime import datetime
-import io  # don't use `codecs` for loading the DB; it will split lines on some IRC formatting
 import logging
 import os
 import re
@@ -21,6 +20,11 @@
 
 from sopel import module, tools
 from sopel.tools.time import format_time, get_timezone, validate_timezone
+
+
+import io  # don't use `codecs` for loading the DB; it will split lines on some IRC formatting
+
+
 
 
 LOGGER = logging.getLogger(__name__)
```
Two spaces before conditional imports:
```diff
 from sopel import module
+
 
 try:
     from ujson import loads
```
and some other spacing oddities.

**Comment by dgw** [comment]
> and some other spacing oddities.

Yep, like two blanks after `__future__`, and sometimes two blanks between other groups.

FWIW I don't actually like squishing the PROJECT and LOCAL groups together, but didn't want to spend time on #1864 fixing that single small niggle. It's literally the only thing I wasn't 100% happy with.

**Comment by Exirel** [comment]
I don't see the point of all of this. You already decided on IRC that you wanted the google-style from flake8, and isort is made to use the PEP8 style. You both expressed that you disliked isort. End of story.

**Comment by dgw** [comment]
The point is that `isort` would be useful, _if_ it could automatically apply _the style we want_. If it can't, fine. We either give up or make an upstream feature request/PR. If it can but we're just not able to find the right options, we need help from someone more familiar with the tool.

**Comment by half-duplex** [comment]
I think isort has other opinions I don't like as well (not just PEP8).
We recorded the current state of things to save time when it's next looked at.

**Comment by Exirel** [comment]
Closing it for now then.

**Pull request closed without merging**
