### PR TITLE
safety: handle missing VirusTotal scan data

### LINKED ISSUE #1850: Safety throws error with positives
### Description
When Safety is enabled with a valid personal free API key whenever a new URL is seen by the bot in a safety enabled channel, it throws an error.

### Reproduction steps
1. Set `safety` to `on` or `strict`
2. Send new message containing a URL

### Expected behavior
What did you expect to happen instead?

### Logs
From the bot
```
<Ad> https://www.cnn.com/2020/04/21/uk/uk-death-toll-coronavirus-statistics-gbr-intl/index.html
<^quark^> [ UK coronavirus: Death toll in England and Wales 41% higher than government figures - CNN ] - www.cnn.com
<^quark^> Unexpected error ('positives') from Ad at 2020-04-21 21:47:29.752477. Message was: https://www.cnn.com/2020/04/21/uk/uk-death-toll-coronavirus-statistics-gbr-intl/index.html
```

From logs
```
[2020-04-21 21:47:29,752] sopel.bot            ERROR    - Unexpected error ('positives') from Ad at 2020-04-21 21:47:29.752477. Message was: https://www.cnn.com/2020/04/21/uk/uk-death-toll-coronavirus-statistics-gbr-intl/index.html
Traceback (most recent call last):
  File "/home/sopel/.local/lib/python3.8/site-packages/sopel-7.0.0-py3.8.egg/sopel/bot.py", line 590, in call
    exit_code = func(sopel, trigger)
  File "/home/sopel/.local/lib/python3.8/site-packages/sopel-7.0.0-py3.8.egg/sopel/modules/safety.py", line 166, in url_handler
    data = {'positives': result['positives'],
KeyError: 'positives'

```

### Environment
- Sopel `.version`: 7.0.1
- Sopel installed via: git 
- Python version: 3.8
- Operating system: alpine
- IRCd `/version`: UnrealIRCd-5.0.3.1
- Relevant plugins: safety

### PR DESCRIPTION
**Pull request by dgw**
### Description
Skip caching the VT result if the two keys we need aren't present. Access those keys using `.get()` with a default value for `KeyError` protection. Fixes #1850.

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
  - Insert my standard disclaimer about local flake8 checks.
- [x] I have tested the functionality of the things this change touches
  - I requested that @adamus1red try this out in my stead, since it's most important to me that this bug is fixed for the user who reported it.

### CODE REVIEW

**Comment by adamus1red** [comment]
@dgw I'll update my container to test it.

**Comment by adamus1red** [comment]
@dgw looks like it's working as expected. ^quark^2 is running the safety-KeyError branch.

```
<Ad> https://secure.eicar.org/eicar.com
<^quark^> [WARNING] link posted by Ad is possibly malicious (confidence 3% - 2/79)
<Ad> https://www.cnn.com/2020/04/21/us/30-hours-phone-call-father-family-coronavirus/index.html
<^quark^> [ His family stayed on the phone for 30 hours -- until he died of Covid-19 - CNN ] - www.cnn.com
<^quark^> Unexpected error ('positives') from Ad at 2020-04-22 19:33:21.750507. Message was: https://www.cnn.com/2020/04/21/us/30-hours-phone-call-father-family-coronavirus/index.html
<-- ^quark^ (~sopel@quark.local) has left #test
--> ^quark^2 (~sopel@quark.local) has joined #test
--- God gives channel operator status to ^quark^2
<Ad> https://www.cnn.com/2020/04/21/us/30-hours-phone-call-father-family-coronavirus/index.html
<^quark^2> [ His family stayed on the phone for 30 hours -- until he died of Covid-19 - CNN ] - www.cnn.com
<Ad> https://secure.eicar.org/eicar.com
<^quark^2> [WARNING] link posted by MrRandom is possibly malicious (confidence 3% - 2/79)
```

**Comment by dgw** [comment]
@adamus1red Probably is, but I should mention that subsequent mentions of the same link will probably hit a different response type (cached analysis from VT, not the "scan queued" type that causes the KeyError) and will look OK even on the old code. The way to test is with a link that VT has never seen before (I just appended some random query params in Postman while checking out the JSON structure).

**Comment by dgw** [comment]
Eh, :shipit:.

**Pull request merged**
