### PR TITLE
Create misspell.yml

### PR DESCRIPTION
**Pull request by adamus1red**
### Description
Automatically check commits for spelling mistakes and creates a PR to fix them.

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [x] I have tested the functionality of the things this change touches

### CODE REVIEW

**Comment by dgw** [comment]
I would very much rather have a `pull_request` check that fails if the patch contains typos, instead of a post-merge check that adds _another_ PR to the queue _after_ a typo has already made it into `master`.

Could such a thing be integrated into `checkstyle.sh`? Maybe with something like [`flake8-spellcheck`](https://pypi.org/project/flake8-spellcheck/).

**Comment by adamus1red** [comment]
> Could such a thing be integrated into `checkstyle.sh`? Maybe with something like [`flake8-spellcheck`](https://pypi.org/project/flake8-spellcheck/).

Should be doable to run `checkstyle.sh` as part of the PR just like the test suite.

**Comment by dgw** [comment]
@adamus1red I see you merged master into this, but what about the alternative approach that would flag new misspellings in PRs _before_ they're merged?

**Comment by dgw** [comment]
NAK a job that will blindly patch typos after they've already made it into the code.

**Pull request closed without merging**
