### PR TITLE
Fix bot.channels.privileges

### LINKED ISSUE #1136: Channel.privileges not being filled in
Every nick in Channel.privileges is being marked as 0 (no privileges).
This needs to be fixed because the docs tell you to use bot.channels over bot.privileges, and some people may become confused by the bot not recognizing anyone as op/voice.

Sopel Version: current master.
Python Version: 3

### PR DESCRIPTION
**Pull request by dgw**
I think I found all the places where `bot.channels` wasn't being updated with privilege info. This should finally resolve #1136, but I would really like another pair of eyes (or three) on this.

Still to do:
- [x] Add tests to verify that `bot.privileges` and `bot.channels.privileges` stay in sync, especially at startup — considering this satisfied by the `assert` added in a21da60.
  - We'll rely on my test instance and early adopters who run Sopel from source on the `master` branch to catch any glaring issues before release.

### CODE REVIEW

**Comment by dgw** [comment]
Perhaps this PR should also add `userhost-in-names` capability to the set Sopel requests? Or maybe that should be done separately.

**Comment by Exirel** [comment]
Yup, lgtm. I used it on another server, added print here and there, and all seem to be fine.

**Comment by dgw** [comment]
(Last time I try managing project cards on my phone, lol. Doesn't work at all. :joy_cat:)

**Comment by Exirel** [comment]
🎉 🎉 🎉

**Pull request merged**
