### PR TITLE
[New module|WIP] Hacker News

### PR DESCRIPTION
**Pull request by psachin**
Depends on https://hacker-news.firebaseio.com

Usage:
.hn <item> <count>

Example:
.hn
.hackernews
.hn stories
.hn newstories 5
.hn beststories 3

Signed-off-by: Sachin Patil <psachin@redhat.com>

### CODE REVIEW

**Comment by maxpowa** [comment]
Should probably be able to handle urls from hacker news, like other modules which are purpose-built for sites do.

`https://news.ycombinator.com/item?id=12196388` - post
`https://news.ycombinator.com/item?id=12197080` - comment

The standard for outputting messages from modules is `[modname] Key: Value | Key2: Value2`, please try to use `|` as much as possible.

**Comment by psachin** [comment]
Yes, I think it is better to show title, post and URL. User reads the title and can decide if he wants to read the discussing on HN or read the post directly by visiting the URL.

> The standard for outputting messages from modules is [modname] Key: Value | Key2: Value2, please try to use | as much as possible.

Sure.

**Comment by psachin** [comment]
@maxpowa any updates ?

**Comment by maxpowa** [comment]
Sorry, we aren't looking to add new default modules at the moment. If you restructure this module to a [sopel-cookiecutter](https://github.com/sopel-irc/sopel-cookiecutter) structure you can distribute it on pypi.

**Pull request closed without merging**
