### PR TITLE
Add correct timezone time in the .in sub-module of the remind module

### PR DESCRIPTION
**Pull request by normcyr**
Correct issue #1036

### CODE REVIEW

**Comment by dgw** [comment]
You need to rebase this branch to remove the unrelated fix to `units` and force-push.

**Comment by normcyr** [comment]
Should be ok now. Sorry for the mistake, I'm learning git ;)

**Comment by dgw** [comment]
Now there are two unrelated commits.

Try this:

````
git rebase -i master
# a text editor will open.
# delete all commits from the list except the line beginning "pick 4089a27"
# save & quit editor; git will perform the rebase
git push -f
````

See https://www.atlassian.com/git/tutorials/rewriting-history#git-rebase-i for more info on this sort of thing. 😃

**Comment by normcyr** [comment]
And now @dgw? Did I follow the proper instructions? (thanks for the help btw)

**Comment by dgw** [comment]
Yep, down to one commit with no unrelated changes. :+1: @normcyr (you're welcome btw)

**Comment by dgw** [comment]
Didn't catch the inaccurate commit message until now, oh well.

**Pull request merged**
