### PR TITLE
remind: remove plugin reimplemented as external package w/better tests

### PR DESCRIPTION
**Pull request by dgw**
### Description
Tin. Development moved to https://github.com/sopel-irc/sopel-remind, with more comprehensive tests and support for running the plugin on Python 3.11+.(built-in has a regex pattern error).

Starting as a draft because of impending merge conflict from #2471 and waiting for a migration path for existing reminders to the new plugin (see sopel-irc/sopel-remind#1).

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
  - (It's very easy to license deletions 😼)
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [x] I have tested the functionality of the things this change touches
  - By which I mean I've tested that `remind` is no longer included with the base Sopel installation, and the test suite was correctly removed (no leftovers causing failures post-deletion)

### CODE REVIEW

**Comment by Exirel** [comment]
Sopel Remind is now available as [a package version 0.1.0](https://pypi.org/project/sopel-remind/0.1.0/)!

**Comment by dgw** [comment]
Just need sopel-irc/sopel-remind#5 to be released and we're set to ship this. I take full responsibility for it not being merged yet, because I'm _still_ making suggestions over there to this day. 😅

(I probably should've left `remind` alone in those recent mypy-cleanup branches to avoid this merge conflict, but it'll be fine.)

**Comment by dgw** [comment]
Migration feature is released upstream! Time to ready this.

**Comment by Exirel** [comment]
And it's done! sopel-remind 0.2.0 is up and allows bot's owner to migrate from the built-in plugin.

**Review by Exirel — APPROVED** [review]
Let's :bomb: :bomb: :bomb: :bomb:  this.

**Pull request merged**
