### PR TITLE
reddit: short url functionality

### LINKED ISSUE #1502: reddit: shortlinks are not handled
Reddit supports (and promotes in the comments page sidebar) a short link format for threads, `http(s)://redd.it/{id}`, where the `id` comes from here in a full-size link: `https://www.reddit.com/r/subreddit/comments/{id}/slugified_thread_title/`.

It should be trivial to add detection and handling of these links in the `reddit` module.

Not assigning to a milestone immediately, because I'd like to release this in a hypothetical version 6.7.0 *if* one happens before 7.0 (but none is planned). It does seem slightly more significant a change than would belong in one of the planned 6.6.x releases, unfortunately.

### PR DESCRIPTION
**Pull request by RustyBower**
- Adding support for shortlinks (e.g. https://redd.it/b1j30r)

Fixes #1502

### CODE REVIEW

**Comment by dgw** [comment]
@RustyBower Easy rebase needed, caused by merging #1508.

**Comment by dgw** [comment]
@RustyBower That's not a rebase, that's a merge. And it broke part of your changes. Notice how the `short_post_regex` callback isn't registered any more?

I could probably fix this one for you, but it's better for you to learn about rebasing (and why merging from upstream is a bad idea in feature branches). :smile_cat:

**Comment by RustyBower** [comment]
Let me give it a whirl :)

**Comment by dgw** [comment]
Can't really merge #1486 "quickly", as it's still in draft status. :laughing: I'd like to get both in ASAP too, though.

**Comment by Exirel** [comment]
Raising priorities since #1505 is blocked by this one.

**Comment by Exirel** [comment]
Meh @ rules, but heh, I guess it's easier the other way around.

**Pull request merged**
