### PR TITLE
pronouns: add `.clearpronouns` command

### LINKED ISSUE #2137: Add `.clearpronouns` command
### The problem
Users might set their pronouns by mistake or just to test the functionality and then they are stuck.

### The solution

Add an "unsetpronouns" that deletes pronoun information for the nick. 
Something like this might work. 

```python
@plugin.command('unsetpronouns')
def unset_pronouns(bot, trigger):
        bot.db.delete_nick_value(trigger.nick, 'pronouns')
```

### PR DESCRIPTION
**Pull request by eliocamp**
### Description

Adds the ability to clear one's pronouns. 

Closes #2137

~~`make qa` reports a bunch of issues but unrelated to my change.~~ @dgw edit: It's because the checks were run on py2, which is no longer supported.

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [x] I have tested the functionality of the things this change touches

### CODE REVIEW

**Comment by dgw** [comment]
> `make qa` reports a bunch of issues but unrelated to my change.

What issues would those be? It shouldn't report anything, and doesn't in CI.

**Comment by eliocamp** [comment]
I get this: 

```
./checkstyle.sh
./sopel.py:2:1: F407 future feature generator_stop is not defined
./pytest_run.py:13:1: F407 future feature generator_stop is not defined
./setup.py:15:13: E999 SyntaxError: invalid syntax
./sopel/trigger.py:2:1: F407 future feature generator_stop is not defined
./sopel/bot.py:8:1: F407 future feature generator_stop is not defined
./sopel/test_tools.py:19:1: F407 future feature generator_stop is not defined
./sopel/web.py:14:1: F407 future feature generator_stop is not defined
./sopel/logger.py:1:1: F407 future feature generator_stop is not defined
./sopel/plugin.py:10:1: F407 future feature generator_stop is not defined
./sopel/loader.py:12:1: F407 future feature generator_stop is not defined
./sopel/coretasks.py:23:1: F407 future feature generator_stop is not defined
./sopel/__init__.py:41:48: E999 SyntaxError: invalid syntax
./sopel/module.py:8:1: F407 future feature generator_stop is not defined
./sopel/formatting.py:8:1: F407 future feature generator_stop is not defined
./sopel/db.py:1:1: F407 future feature generator_stop is not defined
./sopel/tests/factories.py:5:1: F407 future feature generator_stop is not defined
./sopel/tests/pytest_plugin.py:5:1: F407 future feature generator_stop is not defined
./sopel/tests/mocks.py:5:1: F407 future feature generator_stop is not defined
./sopel/tests/__init__.py:5:1: F407 future feature generator_stop is not defined
./sopel/config/core_section.py:1:1: F407 future feature generator_stop is not defined
./sopel/config/types.py:26:1: F407 future feature generator_stop is not defined
./sopel/config/__init__.py:50:1: F407 future feature generator_stop is not defined
./sopel/irc/utils.py:4:1: F407 future feature generator_stop is not defined
./sopel/irc/abstract_backends.py:4:1: F407 future feature generator_stop is not defined
./sopel/irc/isupport.py:14:1: F407 future feature generator_stop is not defined
./sopel/irc/__init__.py:25:1: F407 future feature generator_stop is not defined
./sopel/irc/backends.py:6:1: F407 future feature generator_stop is not defined
./sopel/modules/py.py:8:1: F407 future feature generator_stop is not defined
./sopel/modules/find_updates.py:11:1: F407 future feature generator_stop is not defined
./sopel/modules/choose.py:11:1: F407 future feature generator_stop is not defined
./sopel/modules/adminchannel.py:9:1: F407 future feature generator_stop is not defined
./sopel/modules/rand.py:8:1: F407 future feature generator_stop is not defined
./sopel/modules/tld.py:9:1: F407 future feature generator_stop is not defined
./sopel/modules/bugzilla.py:8:1: F407 future feature generator_stop is not defined
./sopel/modules/units.py:9:1: F407 future feature generator_stop is not defined
./sopel/modules/search.py:9:1: F407 future feature generator_stop is not defined
./sopel/modules/currency.py:9:1: F407 future feature generator_stop is not defined
./sopel/modules/invite.py:9:1: F407 future feature generator_stop is not defined
./sopel/modules/unicode_info.py:9:1: F407 future feature generator_stop is not defined
./sopel/modules/version.py:9:1: F407 future feature generator_stop is not defined
./sopel/modules/find.py:14:1: F407 future feature generator_stop is not defined
./sopel/modules/reddit.py:10:1: F407 future feature generator_stop is not defined
./sopel/modules/admin.py:12:1: F407 future feature generator_stop is not defined
./sopel/modules/wiktionary.py:8:1: F407 future feature generator_stop is not defined
./sopel/modules/url.py:11:1: F407 future feature generator_stop is not defined
./sopel/modules/translate.py:9:1: F407 future feature generator_stop is not defined
./sopel/modules/ip.py:10:1: F407 future feature generator_stop is not defined
./sopel/modules/wikipedia.py:8:1: F407 future feature generator_stop is not defined
./sopel/modules/dice.py:9:1: F407 future feature generator_stop is not defined
./sopel/modules/meetbot.py:9:1: F407 future feature generator_stop is not defined
./sopel/modules/seen.py:10:1: F407 future feature generator_stop is not defined
./sopel/modules/safety.py:8:1: F407 future feature generator_stop is not defined
./sopel/modules/help.py:12:1: F407 future feature generator_stop is not defined
./sopel/modules/pronouns.py:8:1: F407 future feature generator_stop is not defined
./sopel/modules/isup.py:8:1: F407 future feature generator_stop is not defined
./sopel/modules/lmgtfy.py:8:1: F407 future feature generator_stop is not defined
./sopel/modules/__init__.py:1:1: F407 future feature generator_stop is not defined
./sopel/modules/countdown.py:8:1: F407 future feature generator_stop is not defined
./sopel/modules/reload.py:8:1: F407 future feature generator_stop is not defined
./sopel/modules/announce.py:9:1: F407 future feature generator_stop is not defined
./sopel/modules/ping.py:7:1: F407 future feature generator_stop is not defined
./sopel/modules/uptime.py:8:1: F407 future feature generator_stop is not defined
./sopel/modules/calc.py:8:1: F407 future feature generator_stop is not defined
./sopel/modules/remind.py:9:1: F407 future feature generator_stop is not defined
./sopel/modules/xkcd.py:10:1: F407 future feature generator_stop is not defined
./sopel/modules/clock.py:9:1: F407 future feature generator_stop is not defined
./sopel/modules/tell.py:9:1: F407 future feature generator_stop is not defined
./sopel/modules/emoticons.py:8:1: F407 future feature generator_stop is not defined
./sopel/cli/utils.py:1:1: F407 future feature generator_stop is not defined
./sopel/cli/plugins.py:2:1: F407 future feature generator_stop is not defined
./sopel/cli/config.py:2:1: F407 future feature generator_stop is not defined
./sopel/cli/__init__.py:1:1: F407 future feature generator_stop is not defined
./sopel/cli/run.py:36:13: E999 SyntaxError: invalid syntax
./sopel/plugins/jobs.py:17:1: F407 future feature generator_stop is not defined
./sopel/plugins/exceptions.py:5:1: F407 future feature generator_stop is not defined
./sopel/plugins/handlers.py:44:1: F407 future feature generator_stop is not defined
./sopel/plugins/rules.py:1678:22: E999 SyntaxError: invalid syntax
./sopel/plugins/__init__.py:29:1: F407 future feature generator_stop is not defined
./sopel/tools/jobs.py:14:1: F407 future feature generator_stop is not defined
./sopel/tools/_events.py:1:1: F407 future feature generator_stop is not defined
./sopel/tools/calculation.py:2:1: F407 future feature generator_stop is not defined
./sopel/tools/web.py:19:1: F407 future feature generator_stop is not defined
./sopel/tools/target.py:1:1: F407 future feature generator_stop is not defined
./sopel/tools/time.py:2:1: F407 future feature generator_stop is not defined
./sopel/tools/__init__.py:627:23: E999 SyntaxError: invalid syntax
./test/test_config.py:1:1: F407 future feature generator_stop is not defined
./test/test_trigger.py:2:1: F407 future feature generator_stop is not defined
./test/test_irc.py:2:1: F407 future feature generator_stop is not defined
./test/test_tools.py:2:1: F407 future feature generator_stop is not defined
./test/test_bot.py:2:1: F407 future feature generator_stop is not defined
./test/test_db.py:6:1: F407 future feature generator_stop is not defined
./test/test_plugins.py:2:1: F407 future feature generator_stop is not defined
./test/test_coretasks.py:2:1: F407 future feature generator_stop is not defined
./test/test_plugin.py:2:1: F407 future feature generator_stop is not defined
./test/test_formatting.py:2:1: F407 future feature generator_stop is not defined
./test/test_module.py:9:1: F407 future feature generator_stop is not defined
./test/test_loader.py:2:1: F407 future feature generator_stop is not defined
./test/tests/test_tests_mocks.py:2:1: F407 future feature generator_stop is not defined
./test/config/test_config_types.py:1:1: F407 future feature generator_stop is not defined
./test/irc/test_irc_abstract_backends.py:2:1: F407 future feature generator_stop is not defined
./test/irc/test_irc_isupport.py:2:1: F407 future feature generator_stop is not defined
./test/irc/test_irc_utils.py:2:1: F407 future feature generator_stop is not defined
./test/modules/test_modules_url.py:2:1: F407 future feature generator_stop is not defined
./test/modules/test_modules_isup.py:2:1: F407 future feature generator_stop is not defined
./test/modules/test_modules_choose.py:2:1: F407 future feature generator_stop is not defined
./test/modules/test_modules_find_updates.py:2:1: F407 future feature generator_stop is not defined
./test/modules/test_modules_tell.py:2:1: F407 future feature generator_stop is not defined
./test/modules/test_modules_remind.py:2:1: F407 future feature generator_stop is not defined
./test/cli/test_cli_utils.py:2:1: F407 future feature generator_stop is not defined
./test/cli/test_cli_run.py:2:1: F407 future feature generator_stop is not defined
./test/plugins/test_plugins_handlers.py:2:1: F407 future feature generator_stop is not defined
./test/plugins/test_plugins_rules.py:2:1: F407 future feature generator_stop is not defined
./test/tools/test_tools_time.py:2:1: F407 future feature generator_stop is not defined
./test/tools/test_tools_target.py:2:1: F407 future feature generator_stop is not defined
./test/tools/test_tools_web.py:2:1: F407 future feature generator_stop is not defined
./test/tools/test_tools_jobs.py:2:1: F407 future feature generator_stop is not defined
ERROR: flake8 does not pass.
Makefile:6: recipe for target 'quality' failed
make: *** [quality] Error 1
```

**Comment by half-duplex** [comment]
It appears you're using a version of Python older than what Sopel 8+ (`master`) requires, which is 3.6+.

**Comment by dgw** [comment]
OK, all of that (especially `./setup.py:15:13: E999 SyntaxError: invalid syntax`) points to your environment running the checks under Python 2. Sopel 7.1.x will be the last series to support anything below Python 3.6, and much of the `master` branch has already been updated to drop py2.

**Comment by eliocamp** [comment]
Yes, that's it. Changing the default python to python3 now gives me a different error. Horray!

```
./checkstyle.sh
coverage run -m py.test -v .
make: coverage: Command not found
Makefile:10: recipe for target 'test' failed
make: *** [test] Error 127
```

**Comment by dgw** [comment]
So you need to `pip install -r dev-requirements.txt -r requirements.txt` using the correct `pip` command for that version of Python.

**Review by dgw — APPROVED** [review]
Well and good once LGTM re-approves. Took care of the commit message style myself, same as I would have in #2140 if it hadn't been replaced.

**Pull request merged**
