### PR TITLE
reddit: Reduce try/except size for redditor_info

### PR DESCRIPTION
**Pull request by deathbybandaid**
This PR does:
* severely reduce the size of the giant try/except that is `redditor_info`
* move the `is_cakeday` logic to it's own function for potential reusability in future PRs

While `u.id` is not a used variable for `redditor_info`, this PR uses Reddits ID system to verify that a user does exist. Simply put, if a username doesn't have an ID it won't have `.gold` or `.link_karma` or other attributes that would be associated with a redditor.

This also adds a `u.is_employee` check for the message to display when the user is a Reddit employee.

### CODE REVIEW

**Comment by deathbybandaid** [comment]
I will note, that I was originally trying to also determine the difference between accounts that don't exist, and accounts that have been permanently banned.

The praw documentation says that it's possible, but I wasn't able to get it to actually work.
If I get more time, since this will be slated for 7.1, I may try again.

**Comment by dgw** [comment]
> This also adds a `u.is_employee` check for the message (willing to switch color from `PURPLE`) to display when the user is a Reddit employee.

reddit itself uses red to denote site admins speaking officially, FWIW.

**Comment by deathbybandaid** [comment]
Easy enough change when I get a minute

**Comment by deathbybandaid** [comment]
Updated the color

**Pull request merged**
