### PR TITLE
Allow bot to utilize multiple destinations at one time

### PR DESCRIPTION
**Pull request by deathbybandaid**
This adds the ability to send lists of recipients to bot. say/msg/reply/notice to send the same message to multiple destinations/recipients simultaneously.

### CODE REVIEW

**Comment by dgw** [comment]
Leaving this be for now, as @deathbybandaid recently learned about the fact that IRC already supports [sending to multiple destinations at once](https://tools.ietf.org/html/rfc1459#section-4.4.1).

**Comment by deathbybandaid** [comment]
I think this is a pretty good step forward.
#1322 should probably be handled for this to be truly effective.

**Comment by deathbybandaid** [comment]
I have a good idea of what I want to do to tackle issue #1322 . I think it might be better to build that off of this, and not in this commit.

**Comment by deathbybandaid** [comment]
as per

`<+dgw> you know it's probably safest to assume a default target limit of maybe 4, or even 2, if MAXTARGETS (or TARGMAX) isn't defined`

I'm now going to build in a maxtargets value, and maybe by time 
issue #1082 is handled, we can try to draw that value from the server capabilities

**Comment by deathbybandaid** [comment]
I will fix the issues shortly

**Pull request closed without merging**
