### PR TITLE
plugins.handlers: override get_version() for EntryPointPlugin

### PR DESCRIPTION
**Pull request by dgw**
### Description
The `_module` of an entry point plugin is unlikely to have its own `__version__`. What's important is the version of the package from which that entry point was loaded.

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [x] I have tested the functionality of the things this change touches

### Notes
I haven't written a test for this (yet?). Am not even sure if it should call the superclass version (`PyModulePlugin.get_version()`) somewhere as a fallback. Doing that doesn't seem very useful, but I'm open to others' thoughts.

### CODE REVIEW

**Comment by dgw** [comment]
What do you know? The answer was stupid-simple. Still haven't answered the question about calling the superclass's handler, but at least the broken test works now. In real usage, I doubt we'll ever see an entrypoint plugin that doesn't come from a package (as the one in our test suite does), so I haven't tried to test the output. (Should just be "unknown" like a regular module with no `__version__`.)

**Comment by dgw** [comment]
I answered my own `super()` question. Really ready for review now.

**Review by Exirel — APPROVED** [review]
It's OK, I think it should work fine, and if it doesn't there is enough try/except for me to feel confident about this.

I'll add a mental note to write tests for this later.

**Comment by dgw** [comment]
Apparently I forgot to squash this before merging. RIP "Only Checkmarks in the History" goals.

**Pull request merged**
