### PR TITLE
url: bump user-agent

### PR DESCRIPTION
**Pull request by xnaas**
### Description

Update the user-agent string to Chrome 96, the 2nd most popular UA listed on
https://techblog.willshouse.com/2012/01/03/most-common-user-agents/

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
    - [x] I skimmed it, anyway.
- [x] I can and do license this contribution under the EFLv2
- [ ] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [ ] I have tested the functionality of the things this change touches

### CODE REVIEW

**Comment by xnaas** [comment]
In theory this might help get less "are you a robot?" prompts? Bloomberg is at least one site this could be testing against, probably.

**Comment by dgw** [comment]
Don't let me forget about this before the next release, whether it's 7.1.8 or 8.0.0. But I don't want to merge it until we're close to a release, so the UA string doesn't get too stale again waiting for a new package.

We could also think about delegating this to a separate package users can update without needing a new Sopel release. PyPI has a surprisingly high number of packages dedicated to generating fake UAs.

**Comment by xnaas** [comment]
Could also just be a bot owner configurable asset?

Like `.set url.ua Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36`? Dunno; food for thought.

**Comment by dgw** [comment]
There's no `.set` command, but that's beside the point. Some kind of override could make sense if it's not pulled from something that can update as needed, independently of Sopel (or the eventual `sopel-url` plugin this should become).

**Comment by xnaas** [comment]
> There's no `.set` command

*wondering how high dgw is*

**Comment by dgw** [comment]
> > There's no `.set` command
> 
> _wondering how high dgw is_

_sleep-deprived enough to confuse #1986 for an IRC command patch_

**Comment by xnaas** [comment]
Is that what you wanted, @dgw?? 🤔

**Review by dgw — APPROVED** [review]

**Pull request merged**
