### PR TITLE
irc: use deque for "stack" of recent messages

### PR DESCRIPTION
**Pull request by dgw**
### Description
Tin. Reading #2320 made me wonder why we used a list with manual pruning (`l = l[-10:]` after appending), and I couldn't think of a good reason. Updated tests made me pretty confident I could just swap to a deque with `maxlen` and get pruning for free.

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
  - Caveat: Some type-checking stuff gets flagged by flake8, but those should be sorted out already on the actual `master` branch (they reference code that wasn't changed in this patch).
- [x] I have tested the functionality of the things this change touches
  - (thanks to Exirel's updated test suite)

### Notes
This is a draft because it's built on top of #2320. I will rebase and mark ready for review when that's squashed down.

### CODE REVIEW

**Comment by dgw** [comment]
Thanks for breaking CI, Coveralls. Thankfully it doesn't actually matter yet, because this is only a draft.

**Comment by dgw** [comment]
Coveralls is fixed. Still keeping as draft until the base PR is completed.

**Comment by dgw** [comment]
Further discussion on #2320 says we should keep thinking about this, perhaps converting the "stack" to prune messages not just by a dumb count, but by time range and/or maximum size in bytes. This can be considered Replaced if one of us gets the motivation to do the fancy way pre-8.0, but should be merged if we don't.

**Review by SnoopJeDi — APPROVED** [review]
Nice little improvement

**Review by Exirel — APPROVED** [review]
Perfection.

**Pull request merged**
