### PR TITLE
Raspbian 8 support

### PR DESCRIPTION
**Pull request by denics**
Hi guys, thanks for sopel, it is very nice. I was playing with it , and while doing this, I created those .deb to install in my rpi3.
Maybe some more experienced user can also do a complete backport for Jessie

### CODE REVIEW

**Comment by anarcat** [comment]
Hi!

I am the maintainer of the sopel Debian package, and I would be glad to help you with your work.

However, I do not think this is the right place for the .debs to be shipped - the git tree should contain only source code and packages should be built from that.

I have not explicitely backported sopel to jessie, because the backport is mostly trivial (ie. it doesn't require recompiling the package in jessie to be installed) *and* it requires extra dependencies to be shipped, as you have discovered yourself.

I have the following configuration here to make this work easily:

```
[1004]anarcat@marcos:~130$ cat /etc/apt/preferences.d/sopel.pref 
Package: sopel python3-decorator python3-praw
Pin: release n=stretch
Pin-Priority: 990
[1005]anarcat@marcos:~$ cat /etc/apt/preferences.d/stretch.pref 
Package: *
Pin: release n=stretch
Pin-Priority: 1
[1006]anarcat@marcos:~$ cat /etc/apt/sources.list.d/stretch.list 
# Debian jessie binaries and sources
deb http://httpredir.debian.org/debian/ stretch main contrib non-free
deb-src http://httpredir.debian.org/debian/ stretch main contrib non-free
```

If you believe that is too complicated, I could work on making a backport, but since it involves backporting more than just sopel, I was hesitant in bringing in a tree of packages that I would need to maintain in backports in the long term. I am working on packaging 6.4.0 now, and I hope to improve the dependencies so that you can install sopel without having to even use the `praw` and `decorator` dependencies, which then can be installed from `pip` by hand. See the new README.Debian file for more information:

https://anonscm.debian.org/cgit/collab-maint/sopel.git/tree/debian/README.Debian

I believe this pull request should be closed, in any case: this git repository is not the place to ship .debs.

**Comment by denics** [comment]
ok. I'm closing it.

**Comment by anarcat** [comment]
@denics i would be glad to discuss with you how to better integrate sopel in raspbian! let me know if the new package in sid works for you: https://tracker.debian.org/news/799971

**Comment by denics** [comment]
Hi @anarcat thanks for your work! I was just thinking that the rpi is a great place where to run sopel, and that it is a pity it cannot be installed by default. I wanted to upload the .debs here because I do not want to setup a ppa for just sopel, unfortunately I do not have the time. I think that if the package for Jessie (rpi) was made available, probably more users would use it. People using IRC bots are not supposed to know how to make deb packages ;)
Concerning your sid package, it works great on raspbian 8 (jessie) with a couple of glitches:
```
Error loading ipython: No module named 'IPython' (modules/ipython.py:23)
Error loading ip: No module named 'pygeoip' (modules/ip.py:9)
```

when loading and 
```
/usr/lib/python3/dist-packages/sopel/modules/find_updates.py:45: ResourceWarning: unclosed <ssl.SSLSocket fd=6, family=AddressFamily.AF_INET, type=SocketType.SOCK_STREAM, proto=6, laddr=('xxx.xxx.xxx.xxx', 35054), raddr=('yyy.yyy.yyy.yyy', 443)>
  info = requests.get(version_url).json()
/usr/lib/python3/dist-packages/sopel/modules/find_updates.py:45: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketType.SOCK_STREAM, proto=6, laddr=('xxx.xxx.xxx.xxx', 46926), raddr=('yyy.yyy.yyy.yyy', 80)>
  info = requests.get(version_url).json()
```

Let me know how can I further help you,
Denis

**Comment by anarcat** [comment]
On 2016-10-01 07:59:11, Denix wrote:
> Hi @anarcat thanks for your work! I was just thinking that the rpi is
> a great place where to run sopel, and that it is a pity it cannot be
> installed by default. I wanted to upload the .debs here because I do
> not want to setup a ppa for just sopel, unfortunately I do not have
> the time.

I understand. Hopefully with the changes I did, this should not be
necessary anymore.

> I think that if the package for Jessie (rpi) was made available,
> probably more users would use it. People using IRC bots are not
> supposed to know how to make deb packages ;)

Of course, I don't expect people to build their own .debs. ;) What I
think, however, is that people can install the .debs from testing
without too much friction. Since stretch is going into freeze soon and
may be released next year, I am hesitant in uploading stuff to
backports...

> Concerning your sid package, it works great on raspbian 8 (jessie) with a couple of glitches:
> ```
> Error loading ipython: No module named 'IPython' (modules/ipython.py:23)
> Error loading ip: No module named 'pygeoip' (modules/ip.py:9)
> ```

The first warning can be fixed with:

   sudo apt install ipython3

It seems I forgot that one in the README.Debian list. Other plugins
(like reddit, bugzilla and so on have similar issues, documented there.

The second warning can be fixed only with:

    sudo pip3 install pygeoip

> when loading and 
> ```
> /usr/lib/python3/dist-packages/sopel/modules/find_updates.py:45: ResourceWarning: unclosed <ssl.SSLSocket fd=6, family=AddressFamily.AF_INET, type=SocketType.SOCK_STREAM, proto=6, laddr=('xxx.xxx.xxx.xxx', 35054), raddr=('yyy.yyy.yyy.yyy', 443)>
>   info = requests.get(version_url).json()
> /usr/lib/python3/dist-packages/sopel/modules/find_updates.py:45: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketType.SOCK_STREAM, proto=6, laddr=('xxx.xxx.xxx.xxx', 46926), raddr=('yyy.yyy.yyy.yyy', 80)>
>   info = requests.get(version_url).json()
> ```

So that's a warning that is in the upstream requests code, and not
specifically related to sopel, iirc.

https://github.com/kennethreitz/requests/issues/1882

It is fixed by upgrading requests - you can also just ignore those
warnings.

Hopefully that package will work for you!

a.
-- 
Religion is like a blind man looking in a black room for a black cat
that isn't there, and finding it.
                         - Oscar Wilde

**Pull request closed without merging**
