### PR TITLE
[db] Use IF NOT EXISTS when creating tables

### PR DESCRIPTION
**Pull request by fatalis**

### CODE REVIEW

**Comment by thomastanck** [comment]
+1 code is now cleaner and more robust. Small change that doesn't hurt

**Comment by dgw** [comment]
That's not a rebase, it's a merge from upstream.

**Comment by fatalis** [comment]
Woops, first time using githubs built in conflict resolver, fixed.

**Comment by dgw** [comment]
GitHub's web UI can't be trusted to do much of anything "the right way", honestly. I just never even try any more and use the command line.

Thanks for squaring this away, it'll be merged when the time comes. :+1:

**Pull request merged**
