### PR TITLE
pronouns: Ignore whitespace

### PR DESCRIPTION
**Pull request by nfearnley**
Changed trigger.group(2) to trigger.group(2).strip() in order to ignore trailing whitespace. (Occurs when user uses tab completion). Also fixed issue where wrong nick is given when pronouns are requested.

### CODE REVIEW

**Comment by dgw** [comment]
Can also use `trigger.group(3)`.

**Comment by nfearnley** [comment]
That was my initial thought, but I decided .strip() was more explicit and
easier to understand. Either method would work.

**Comment by dgw** [comment]
The reason I suggest using group 3 is because it can't be more than one word. `trigger.group(2).strip()` can still contain multiple words, but nicks can't have spaces in them.

**Comment by nfearnley** [comment]
Works for me.

**Comment by dgw** [comment]
What I mean is this:

````
<dgw> .pronouns
<Sopel> dgw: I don't know your pronouns! You can set them with .setpronouns
<dgw> .setpronouns he
<Sopel> dgw: Thanks for telling me!
<dgw> .pronouns
<Sopel> dgw's pronouns are he/him/his/his/himself. See http://pronoun.is/he for examples.
<dgw> .pronouns dgw
<Sopel> dgw's pronouns are he/him/his/his/himself. See http://pronoun.is/he for examples.
<dgw> .pronouns dgw dgw
<Sopel> I don't know dgw dgw's pronouns. They can set them with .setpronouns
````

Any extraneous word(s) after the nickname breaks it. May or may not be of concern here, but all (most?) modules I wrote for myself use groups 3+ to avoid this when taking single-words arguments.

**Comment by maxpowa** [comment]
Another solution would be to `split()` group 2, and then list off all
matches from that array.

**Pull request closed without merging**
