### PR TITLE
Resolve #926

### LINKED ISSUE #926: Remove feedparser dependency
The weather module needlessly uses `feedparser` for some things, which adds a needless (python3-incompatible) dependency. It should be done with straight XML processing, instead.

### PR DESCRIPTION
**Pull request by maxpowa**
Also cleaned up dict value retrieval a little, the .get() calls were a bit unnecessary.

### CODE REVIEW

**Comment by dgw** [comment]
Should probably be squashed into a single commit that says "Removed feedparser dependency (closes #926)" or something like that. But :+1:

**Comment by maxpowa** [comment]
But muh commiting from github web

**Comment by dgw** [comment]
That sounds painful lol

**Comment by embolalia** [comment]
The `get` calls are necessary, because the result will not always have those keys in it. `get` will return `None`, rather than raising a `KeyError`.

**Comment by maxpowa** [comment]
Ah good call, didn't even think about that. Should I edit this PR or create a new one to add them back in?

**Comment by embolalia** [comment]
You can just edit this one. Thanks!

**Comment by embolalia** [comment]
I got this exception while testing this with `.weather new york, ny`:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xmltodict.py", line 246, in parse
    parser.ParseFile(xml_input)
TypeError: argument must have 'read' attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/embo/src/willie/sopel/bot.py", line 262, in call
    exit_code = func(sopel, trigger)
  File "/home/embo/src/willie/sopel/modules/weather.py", line 147, in weather
    parsed = xmltodict.parse(url).get('rss')
  File "/usr/local/lib/python3.4/dist-packages/xmltodict.py", line 248, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 5
```

**Comment by maxpowa** [comment]
Yeaaaah, don't ask how that one slipped through.

**Comment by embolalia** [comment]
Thanks!

**Pull request merged**
