### PR TITLE
spellcheck: add examples

### PR DESCRIPTION
**Pull request by torstehu**

### CODE REVIEW

**Comment by HumorBaby** [comment]
Since this is a spellcheck module, the typo is actually intentional 😄 If the command is run as is (with "typo"), it will demonstrate how the bot responds to incorrectly spelled words

**Comment by HumorBaby** [comment]
It may be helpful to add examples outputs to the `@example` decoration to 1) prevent such confusion regarding the examples, and 2) show what expected output is when (a) `wrod` is spelled incorrectly, and (b) `word` is spelled correctly.

The relevant arguments to the `@example` decorator:
https://github.com/sopel-irc/sopel/blob/95812b540e082ff9d24fbd77c19662349ab119e3/sopel/module.py#L428-L440

In use:
https://github.com/sopel-irc/sopel/blob/ca0250188cb08efb05ae9db39dbaf573c55775b5/sopel/modules/emoticons.py#L14


So, @torstehu, building off your current suggested change, adding another `@example` with `wrod` and adding expected `result`s for both `@example`s are needed for this PR, IMO.

**Comment by torstehu** [comment]
@HumorBaby Thanks for the clarification, I have tried to make some examples with one and two words, can you give me some comments on this commit?

**Comment by dgw** [comment]
I'm confused now, because I thought I included example tests in #1164. Wonder what happened to them… \*digs around local repos\*

**Comment by Exirel** [comment]
All these looks good! :tada: :shipit:

**Comment by dgw** [comment]
> The examples I wrote must be stashed on my office computer

Or not. I have no idea where they went, then.

@Exirel did you want to formally approve this, or let me take full responsibility? :P

**Comment by Exirel** [comment]
> let me take full responsibility? :P

Yes. :stuck_out_tongue:

**Comment by Exirel** [comment]
@dgw I wonder if I should create a label "easy to merge" for you to check... ;-)

**Comment by dgw** [comment]
@Exirel It wouldn't speed up my merging pace, lol. I just don't like merging too much at once.

**Pull request merged**
