### PR TITLE
TLS root cert fixes

### PR DESCRIPTION
**Pull request by tpltnt**
Hi there,

I documented and rewrote `_find_certs()` to support more platforms and be easier to extend. This PR was inspired by issue #1246.

Cheers
tpltnt

### CODE REVIEW

**Comment by kitten77** [comment]
good fix :)

**Comment by dgw** [comment]
@kitten77 Did applying this fix #1246 for you?

**Comment by anarcat** [comment]
there's a python package just for that which we might consider instead, [certifi](https://pypi.python.org/pypi/certifi/).

**Comment by dgw** [comment]
We can consider it, but the certifi documentation site is unavailable at the moment (and has been since November), which doesn't exactly make me want to jump on it.

**Comment by alanhuang122** [comment]
`certifi` is a dependency for `requests`, so it's already available, FYI - it's not a separate package

**Comment by anarcat** [comment]
> We can consider it, but the certifi documentation site is unavailable at the moment (and has been since November), which doesn't exactly make me want to jump on it.

This is just a domain registration issue, documented here: https://github.com/certifi/python-certifi/issues/78

I wouldn't block on this: certifi is widely distributed, and rolling our own is a serious challenge that I don't think is within the scope of this project.

**Comment by alanhuang122** [comment]
So, my two cents - what happens if (when) there are changes to the root certificate store? Python packages don't get updated automatically, so even though `certifi` tracks changes to the Mozilla trust store, it doesn't get updated when the system `ca-certificates` file does.

**Comment by anarcat** [comment]
On 2018-03-24 15:28:45, Alan Huang wrote:
> So, my two cents - what happens if (when) there are changes to the root certificate store? Python packages don't get updated automatically, so even though `certifi` tracks changes to the Mozilla trust store, it doesn't get updated when the system `ca-certificates` file does.

I believe certifi uses the system trust store when available.

a.

**Comment by kitten77** [comment]
@dgw yes it looks good for me thanks :)

**Pull request merged**
