### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by simark**

### CODE REVIEW

**Comment by tpltnt** [comment]
What is blocking this PR? It does look pretty simple.

**Comment by dgw** [comment]
Same as what's blocking all the open PRs: no active maintainers exist. That could change, but Sopel might also just be a dead project if getting new maintainers doesn't work out.

**Comment by dgw** [comment]
Plot twist: I'm the new maintainer. Merging.

**Comment by simark** [comment]
Hurry, thanks!

**Comment by tpltnt** [comment]
Yay plot twist \o/

**Pull request merged**
