### PR TITLE
lmgtfy: add examples with tests

### PR DESCRIPTION
**Pull request by Exirel**
Adds 3 examples for testing purpose.

### CODE REVIEW

**Comment by dgw** [comment]
I just noticed Coveralls' status report: "Coverage decreased (-0.3%) to 42.331%"

How does a PR that _adds_ tests somehow _decrease_ coverage?! :laughing:

**Comment by Exirel** [comment]
Probably because Coveralls compare to the previous run, which might be a PR with more tests added. But that doesn't matter that much. :)

**Comment by dgw** [comment]
_That's_ what it does? For almost a year, I've been thinking it was quite a bit smarter than that.
The more you know… lol

**Comment by Exirel** [comment]
I did an upstream update hence the rebase/force push here.

**Comment by dgw** [comment]
:+1:

Though for what it's worth, I don't mind merging from branches that aren't based on current master unless there are conflicts. Just letting you know in case you want to save a few minutes here and there on open PRs. :)

**Pull request merged**
