### PR TITLE
dev: adds (optional) pre-commit and pre-push Git hooks

### PR DESCRIPTION
**Pull request by HumorBaby**
Please allow me to sell this PR to you:

**INFORMERCIAL**
_Based on true stories of HumorBaby's own experiences_
```
INT. A SOPEL DEVELOPER'S DESK

A developer is happily Sopelunking away. The developer pushes a commit to a PR branch, 
opens the PR in a broswer and sit's back waiting for CI (and more importantly, reviews!)...

        VOICEOVER
    Has this ever happened to you?!
    
The status check changes to "[X] Travis CI - Pull Request — Build Failed". 
The developer starts frantically checking the Travis logs to see what went wrong.
The developer is not physically hurt, but is emotionally devastated.

        VOICEOVER (CONT'D)
    You wrote some code, but various checks failed after you pushed to your repo?
  
The developer looks towards the screen.

        DEVELOPER
    I always forget to run code quality and tests! **Travis does so much extra
    work because of me...**

A fist pops out of the developer's monitor (The Ring style) and punches the
developer in the back of the head.
A giant red X appears over the developer, indicating they should never write
another line of code again.

        VOICEOVER
    Hashtag never again!
    Sopel, now with Git hooks built-in!
    Pretty colors included!
...
```

### CODE REVIEW

**Comment by HumorBaby** [comment]
These (optional)<sup>[1]</sup> git hooks will, by default:
- Run `./checkstyle.sh` pre-commit
- Run `python pytest_run.py` pre-push

The hooks can always be disabled by appending `--no-verify` to your `git ...` command, but they are also customizable!

Set `SKIP_CHECKSTYLE=1` or `SKIP_PYTEST=1` for your git command to skip a given test, but still run the hooks. 

`pre-commit` and `pre-push` will only run one of the two possible checks; explicitly set `SKIP_CHECKSTYLE=0` or `SKIP_PYTEST=0` to ensure both checks run for each hook, respectively.

-----
<sup>[1]</sup> Hooks are activated with `make init`, which can be run at developer's discretion.

**Comment by HumorBaby** [comment]
> So, as a compromise, would you please consider not using make init to install them?
I would rather see make install-hook and make uninstall-hook instead.

Of course! Uses `make install-hooks` and `make uninstall-hooks` instead.

> Also, why .githooks? Why not contrib/githooks instead?

`contrib/githooks` makes much more sense :smile:. Done.

At this point, I usually am manually running checkstyle and pytest around every save anyway. These hooks just serve as a final fail-safe for silly mistakes for me.

**Comment by HumorBaby** [comment]
- [ ] Amending commit messages to follow convention (and applying fixups) now that PR is approved

**Comment by dgw** [comment]
\> Merge conflict
💤

@HumorBaby, if you wouldn't mind…

**Comment by HumorBaby** [comment]
image

... just waiting on my work to be _Scrutinized_ :crossed_fingers:

**Pull request merged**
