### PR TITLE
help module - remove duplicates

### PR DESCRIPTION
**Pull request by lenisko**
Remove duplicates in help output. They are showing itself after plugin reload/unload... I don't really remember but worth taking care as well ;-)

### CODE REVIEW

**Comment by dgw** [comment]
@hekel I can't formally request a review from you using GitHub's UI, but can you look at this?

**Comment by lenisko** [comment]
@dgw nothing to test I guess

```python
>>> cmds = ['1', '2', '3', '3']
>>> '  '.join(cmds)
'1 2 3 3'
>>> cmds = set(cmds)
>>> '  '.join(cmds)
'2 1 3'
```

unless we care about order

**Comment by dgw** [comment]
@lenisko The commands aren't sorted anyway, so nbd about the order. What I am worried about is the duplicated output being a small symptom of a bigger issue. Do duplicated commands run multiple times? If so, please do open an issue for that specifically (or search for one; I haven't finished going through all the open stuff yet).

**Comment by lenisko** [comment]
@dgw Tbh I'm on my own fork so don't had a chance to test it atm. 
If you want to check it, try logging `cmds` to console and make few `.plugin reload x`, `.help x` I think you should see commands `y` times where `y` is amount of reloads.

**Pull request merged**
