### PR TITLE
Instagram

### PR DESCRIPTION
**Pull request by kwaaak**

### CODE REVIEW

**Comment by kwaaak** [comment]
Oops, this was a bad click

**Comment by dgw** [comment]
@kwaaak You can fix it by rebasing on master and keeping only 123ae6f. Force-push to your `instagram` branch and it's all good.

**Comment by kwaaak** [comment]
One of these days I have to learn git

**Comment by dgw** [comment]
It's pretty simple if you already have git available in your terminal.

````
cd /path/to/sopel/repo
git checkout instagram
git rebase -i master
# Here, a text editor will open, probably vi/vim
# Remove all the lines (`dd`) that don't represent the commit you want, then type `:wq<enter>`
# git will perform the rebase, dropping the commits you removed from the list
git push -f origin instagram
# The repo will be updated
````

I've made some assumptions (you already have your sopel repo cloned locally, you already have git installed in your local terminal, and that vi/vim is your shell's default text editor), but even if your environment is different it should get you on the right track.

You can also learn a lot from simple tutorials, like https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

**Comment by kwaaak** [comment]
Thanks for helping me, I had just figured it out via https://help.github.com/articles/using-git-rebase-on-the-command-line/

**Comment by dgw** [comment]
Congrats!

GitHub would have allowed reopening this PR, actually, but I forgot to mention it. I'll give #1260 a look when I have the chance.

**Comment by kwaaak** [comment]
The button was greyed out and said something about there being a forced push

**Comment by dgw** [comment]
That's interesting, since now it says I can't reopen because there's already an open pull request from the same branch. It probably would have worked if the PR was reopened, then the branch force-pushed. Doing it the other way around (which I told you to do) broke it :laughing:

Both of us are learning stuff, which is great :)

**Pull request closed without merging**
