### PR TITLE
Support geoip lookup for IPv6 and nicknames

### PR DESCRIPTION
**Pull request by kwaaak**

### CODE REVIEW

**Comment by kwaaak** [comment]
Adds functionality anticipated in https://github.com/sopel-irc/sopel/issues/945

**Comment by kwaaak** [comment]
@dgw 6.6.0 :)

Been running this for 2 years with no issues

**Comment by dgw** [comment]
Running for 2 years is a good testament to the code's stability.

I would just ask that you exercise your newly found rebasing skills and remove that empty merge commit (34af68d) which adds nothing to the history. :)

**Comment by dgw** [comment]
@kwaaak You didn't have to completely squash out all the history, haha. But it's probably not really worth the hoops you'd have to jump through to get the original history back. Just as long as the current state includes all the changes you wanted to submit for this PR, it's fine.

**Comment by kwaaak** [comment]
https://github.com/sopel-irc/sopel/issues/505 might be a feature for the future
https://github.com/sopel-irc/sopel/issues/346 this alerted me to some changes in the near-future which require a short review and update to the module: https://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by dgw** [comment]
@kwaaak I recovered and cleaned up the history with a series of rebase passes, and brought the branch up to date with `master` as long as I was at it. Let me know if anything in the rewritten history looks wrong.

Are you going to handle #346 in a future PR?

**Comment by kwaaak** [comment]
I think so, "future" meaning "once this breaks" :)

**Comment by dgw** [comment]
> "future" meaning "once this breaks"

Hopefully it'll be sooner than that! We have deadlines readily available for when the old GeoLite Legacy database builds will become unavailable, and there's ample time for a smooth transition. (I'll post details in the other issue.)

**Pull request merged**
