### PR TITLE
db, test: do not create nick ID by default

### PR DESCRIPTION
**Pull request by dgw**
Having `get_nick_id()` default to `create=True` may cause unexpected behavior if invalid nicknames are passed to it via plugins' use of the getter and setter methods.

We are taking this opportunity to fix the API design itself, with no period of deprecation and warnings, since this particular method is mostly used only by the database object itself, and isn't really intended for direct use by plugins.

I've also added some more assertions and error-case checking to some of the related tests for `sopel.db`. The tests required minimal changes to continue passing; only cases where some manual setup was using `get_nick_id()` as a shortcut to make sure the nick would exist in the database before running the test case needed to be changed.

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [x] I have tested the functionality of the things this change touches

### Notes
A code search on GitHub for `get_nick_id` returned very few results that weren't either a Sopel plugin or a clone of Sopel itself being used as the base for a custom bot. Of the results that were actually plugin code, only one out of a dozen or so might be problematic (and I will open an issue on that repo to let the author know about this planned change).

As I thought, not many people actually use this function directly. At least half the plugin results were from _my_ plugins or modified clones thereof (which already used `create=False` explicitly).

### CODE REVIEW

**Comment by dgw** [comment]
This CI failure is what you were talking about in #2227, eh, @Exirel?

**Comment by Exirel** [comment]
> This CI failure is what you were talking about in #2227, eh, @Exirel?

Yes. I'm trying to fix it, it's almost done.

**Comment by Exirel** [comment]
Oh, this will conflict with #2231 a lot. 😁

**Review by Exirel — APPROVED** [review]

**Comment by dgw** [comment]
> Oh, this will conflict with #2231 a lot. 😁

Heh, #2231 already has conflicts from merging #2233, so what's a little more? 😏 (And it looks to me like most of the conflict will come from type-hinting, not the actual changes to support "smart" identifiers, so really you did it to yourself. 😛)

**Comment by dgw** [comment]
Figured if I merge sooner, you can assess + fix the conflicts sooner. 😸

**Comment by Exirel** [comment]
Is that a permission to rebase right now? 😁

**Comment by dgw** [comment]
"As they say in the Temporal Mechanics department, 'There's no time like the present.'"

**Pull request merged**
