### PR TITLE
search: quote URL parameters

### PR DESCRIPTION
**Pull request by Exirel**
**Note**: quick fix for 6.6.x

Following #1480 my eyes turned to the search module, and they found the same kind of problems.

So I applied the same solution, and it works fine:

    <@Exirel> .suggest 2+2
    <Sopel> 4
    <@Exirel> .suggest coup d'ét
    <Sopel> coup d'état

_(also yes, I'm so French that I can't resi**s**t to use "coup d'état" in my example)_

### CODE REVIEW

**Comment by Exirel** [comment]
Ah! Gotta fix the checkstyle first.

**Comment by dgw** [comment]
> _I can't resit_

resist?

_(spoiler: I'm going to say the same thing I did in #1480 about your commit message(s) in PR review :stuck_out_tongue:)_

**Comment by Exirel** [comment]
> _(spoiler)_

I deserve that 100% my fault.

**Comment by Exirel** [comment]
> I also am a little curious why you went with `requests.get`'s parameter handling for this, but `sopel.web.quote()` in #1480.

Because in #1480 the "word" is part of the URL's path, and not the URL's query string: `requests.get` encode the query string parameters, but doesn't touch the URL itself.

As for the 's'... I've no excuse.

**Comment by dgw** [comment]
Fair enough on query params vs. URL path components.

Also, I forgot to ask: Did you intentionally remove the comment about #885? We probably don't need it, honestly, but I was surprised to see it removed in the diff.

**Comment by Exirel** [comment]
I did, because query parameters **must** be encoded. If it was a weird quirk, the comment would be relevant, but it isn't: there was a bug because the query parameter wasn't encoded properly.

**Comment by Exirel** [comment]
@dgw should be good now.

**Pull request merged**
