### PR TITLE
FIX: Bugzilla module issues

### PR DESCRIPTION
**Pull request by anewmanRH**

### CODE REVIEW

**Comment by maxpowa** [comment]
Might be a bit cleaner to just do 
```
if error:
    print('Bugzilla error: ' + error)
    return
```
instead of cramming all the code inside the if block. Also, since the function is listening for urls, it should be fine to not say anything back to the channel (see url.py when it fails to find a title in the page).

**Comment by embolalia** [comment]
Yeah, I think @maxpowa is right here. I think probably the best thing to do would be to do `if error: return` right away, rather than outputting a message.

**Comment by anewmanRH** [comment]
Updated as suggested.

**Comment by maxpowa** [comment]
+1

**Comment by elad661** [comment]
Can you squash the commits for easier reviewing and cleaner git history?

**Comment by anewmanRH** [comment]
Squashed as requested.

**Comment by anewmanRH** [comment]
Fixed the logger issue, please merge.

**Pull request merged**
