### PR TITLE
url: Say something on .title command failure

### LINKED ISSUE #1340: .title command should say an error if no title is found
Example: http://zimage.com/~ant/temp/notitle.html

Sopel should say there was no web page title found.

### PR DESCRIPTION
**Pull request by dgw**
Bit weird in its handling of failure when multiple URLs were passed in, admittedly, but figuring out which URL failed would require a refactor.

Fixes #1340.

@antdude what do you think of this solution?

### CODE REVIEW

**Comment by antdude** [comment]
@dgw Uh, what is the solution?

**Comment by dgw** [comment]
@antdude It's this:

https://github.com/sopel-irc/sopel/blob/5868cc6c9ab5e75f0227891823c357b61ec18031/sopel/modules/url.py#L109-L112

`.title https://link.invalid/blah/` -> Error that Sopel couldn't fetch it.

`.title https://link.invalid/working/ https://link.invalid/not-working/` -> Error that Sopel couldn't fetch all of the URLs' titles (but can't be specific about which without a major rewrite).

**Comment by antdude** [comment]
@dgw Thanks. I downloaded https://raw.githubusercontent.com/sopel-irc/sopel/5868cc6c9ab5e75f0227891823c357b61ec18031/sopel/modules/url.py into my /home/ant/SopelPython3/lib/python3.4/site-packages/sopel/modules (made a back up of the old url.py file).  I exited and relaunched my Sopel v6.5.3 and retested with http://zimage.com/~ant/temp/notitle.html URL. My bot didn't show anything from it. Is it supposed to show nothing? I thought it was supposed to tell me there is no title for that URL.

**Comment by dgw** [comment]
It will not say anything unless you issued the `.title` command:

````
21:41:52 <~dgw>  .title http://zimage.com/~ant/temp/notitle.html
21:41:52 <Sopel>  dgw: Sorry, fetching that title failed. Make sure the site is working.
21:43:01 <~dgw>  .title http://zimage.com/~ant/temp/notitle.html https://www.google.com/
21:43:01 <Sopel>  dgw: [ Google ] - www.google.com
21:43:03 <Sopel>  dgw: I couldn't get all of the titles, but I fetched what I could!
````

URLs alone, without the command, will fail silently to reduce channel noise.

**Comment by antdude** [comment]
@dgw Ah, thanks. Can we get this for URL parsers too?

**Comment by dgw** [comment]
No, I said (https://github.com/sopel-irc/sopel/issues/1340#issuecomment-394877806) that only the command will get the error message in the discussion at #1340. Automatic title-fetching will remain silent on errors.

**Comment by antdude** [comment]
Hmm. OK if you say so. I think it would be nice for automatic title fetching to show the same.

**Comment by dgw** [comment]
I don't like the idea of Sopel spitting out an error when not explicitly called on via command. Auto-fetching URL titles is meant to be a value-add; error messages add no value to the chat.

There's also the matter of Sopel not (currently) being able to say _which_ URL's title couldn't be fetched. As mentioned above, the ability to specify which URL failed would require a pretty extensive rewrite.

**Pull request merged**
