### PR TITLE
add userserv auth method

### LINKED ISSUE #1237: Chanserv auth_method?
Is there an option for the [auth_method](https://sopel.chat/docs/config.html#the-core-configuration-section) that's equivalent to `chanserv`?

### PR DESCRIPTION
**Pull request by wgordon17**
Closes #1237

### CODE REVIEW

**Comment by wgordon17** [comment]
The test failures are not caused by my PR

**Comment by wgordon17** [comment]
@dgw Is it possible to have this PR merged?

**Comment by dgw** [comment]
@wgordon17 Yes, but not by me. Pinging @embolalia for inclusion in the next release, if possible.

**Comment by wgordon17** [comment]
Thank you!

Thanks,

WILL GORDON

COMMUNITY ENABLEMENT - OPENSHIFT

Red Hat North Carolina <https://www.redhat.com/>

100 E Davie St
<https://red.ht/sig>
TRIED. TESTED. TRUSTED. <https://redhat.com/trusted>

**Comment by wgordon17** [comment]
@embolalia It would be great if this were available in the next release. I guess I didn't realize this, but this is actually a duplicate of #1217. I leave it up to you to decide which PR get's accepted =)

**Comment by dgw** [comment]
I think #1217 wins just by being first (and because it alphabetizes the options, which I like).

**Pull request closed without merging**
