### PR TITLE
[ping] Stop Sopel from replying rudely to the bot's owner.

### PR DESCRIPTION
**Pull request by DMzda**
Stop Sopel from replying rudely to the bot's owner in ping.py:

    <@dmzda> hi dmbot 
    <dmbot> Fuck off, dmzda

### CODE REVIEW

**Comment by dgw** [comment]
Could be a setting, but the current behavior is amusing enough that I'd rather not see it gone. :-1:

**Comment by embolalia** [comment]
The number of people who would bother configuring it, rather than just replacing the module, is rather small, I think. And while it might be amusing to some people, it's annoying to others. It doesn't belong in the default module set.

Thanks for the PR, @DMzda.

**Comment by DMzda** [comment]
I had written the code to make this a config option called `be_nice` before I saw that this was merged, is that something you're interested in @embolalia ?

**Comment by embolalia** [comment]
I don't think it would be worthwhile to include in the default module set. If you want to make your own module for that, feel free, but I don't think we'll pull it in.

**Pull request merged**
