### PR TITLE
allow find_url to parse the content directly

### PR DESCRIPTION
**Pull request by anarcat**
this makes find_title() a little more useful for outside tools.

### CODE REVIEW

**Comment by anarcat** [comment]
bump.

**Comment by embolalia** [comment]
What do you mean by "outside tools"? Can you provide the use case for this?

**Comment by anarcat** [comment]
the use case is for contrib module to use this. i have tried to use it in the bookie plugin for example.

**Comment by maxpowa** [comment]
The import system is currently too unreliable to make this reasonable. If the module that imports url is loaded before url itself, it will fail to import. This already happens with occasionally with xkcd.py because it imports search. There's been no activity on this for over a year so I'm going to close it.

**Pull request closed without merging**
