### PR TITLE
[New Module|WIP] Karma module for Sopel

### PR DESCRIPTION
**Pull request by psachin**
- Removed rate() <- time-delay
- Handles string such as 'psachin++ great!'

Todo:
- Should handle string such as 'Cool, psachin++ great!'

### CODE REVIEW

**Comment by psachin** [comment]
@maxpowa Now this is somthing where I need you help/suggestion. As you see, string like 'Cool, psachin++ great!' doesn't get parse.

I have following cases to test with.
```
foo bar sometext psachin++ asa
tas++toona++
sopel
eck++ great!
hooya++ anande++
sansa hooya++ anande++
foobar hooya++ anande++ sometext
psachin+-
psachin--
psachin++sansa++
```
Also, if see that last line, both niks should be in .group(). But I think handling multiple nicks should not be a problem.

**Comment by dasu** [comment]
'c++ is the worst' will trigger it, and notepad++ will too.
maybe have a check to see that the nick actually exists in the channel using bot.channels[trigger.sender.lower()].users to get a list of users and checking if the trigger is in the list?

**Comment by psachin** [comment]
@dasu 
Even `bot.channels[trigger.sender.lower()].users` don't output anything for strings like,

```
foo bar sometext psachin++ asa
foobar hooya++ anande++ sometext
```
 
I don't think this has to do anything with existence of nick

**Comment by maxpowa** [comment]
@psachin You'd probably have to do a second regex search on the matched string to get multiple nicks as Sopel's `@rule` only grabs the first match in the string.

**Comment by psachin** [comment]
@maxpowa Adding multiple `@rule` will cause it to trigger multiple times. That should add more complexity. The latest commit can handle multiple nicks. ;)

Now only thing remains is, why string like
```
'Cool, psachin++ great!'
```
is not handled. Any idea?

**Comment by maxpowa** [comment]
It's likely because the ++ bit is in the middle of the string and your regex doesn't have fuzzy matches around it. 

I'm going to close this though because we aren't looking to add new default modules at the moment. If you restructure this module to a [sopel-cookiecutter](https://github.com/sopel-irc/sopel-cookiecutter) structure you can distribute it on pypi.

**Pull request closed without merging**
